function H = computeRho_s2(x,y,z,u,v,w,xs2,ys2,zs2,theta,thetadot)
%computeRho_s2
%    H = computeRho_s2(X,Y,Z,U,V,W,XS2,YS2,ZS2,THETA,THETADOT)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Feb-2024 16:49:07

t2 = cos(theta);
t3 = sin(theta);
t4 = x.^2;
t5 = xs2.^2;
t6 = y.^2;
t7 = ys2.^2;
t8 = z.^2;
t9 = zs2.^2;
t10 = x.*xs2.*2.0;
t11 = x.*ys2.*2.0;
t12 = xs2.*y.*2.0;
t13 = y.*ys2.*2.0;
t14 = z.*zs2.*2.0;
t15 = -t12;
t16 = -t14;
t17 = t10+t13;
t18 = t11+t15;
t19 = t2.*t17;
t20 = t3.*t18;
t21 = -t19;
t22 = t4+t5+t6+t7+t8+t9+t16+t20+t21;
H = [sqrt(t22);1.0./sqrt(t22).*(u.*x+v.*y+w.*z-w.*zs2-t2.*(u.*xs2+v.*ys2)+t3.*(u.*ys2-v.*xs2)+t2.*thetadot.*(x.*ys2-xs2.*y)+t3.*thetadot.*(x.*xs2+y.*ys2))];
