function H = computeRho_s3(x,y,z,u,v,w,xs3,ys3,zs3,theta,thetadot)
%computeRho_s3
%    H = computeRho_s3(X,Y,Z,U,V,W,XS3,YS3,ZS3,THETA,THETADOT)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    13-Mar-2024 19:27:41

t2 = cos(theta);
t3 = sin(theta);
t4 = x.^2;
t5 = xs3.^2;
t6 = y.^2;
t7 = ys3.^2;
t8 = z.^2;
t9 = zs3.^2;
t10 = x.*xs3.*2.0;
t11 = x.*ys3.*2.0;
t12 = xs3.*y.*2.0;
t13 = y.*ys3.*2.0;
t14 = z.*zs3.*2.0;
t15 = -t12;
t16 = -t14;
t17 = t10+t13;
t18 = t11+t15;
t19 = t2.*t17;
t20 = t3.*t18;
t21 = -t19;
t22 = t4+t5+t6+t7+t8+t9+t16+t20+t21;
H = [sqrt(t22);1.0./sqrt(t22).*(u.*x+v.*y+w.*z-w.*zs3-t2.*(u.*xs3+v.*ys3)+t3.*(u.*ys3-v.*xs3)+t2.*thetadot.*(x.*ys3-xs3.*y)+t3.*thetadot.*(x.*xs3+y.*ys3))];
