function H = computeRho_s1(x,y,z,u,v,w,xs1,ys1,zs1,theta,thetadot)
%computeRho_s1
%    H = computeRho_s1(X,Y,Z,U,V,W,XS1,YS1,ZS1,THETA,THETADOT)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Mar-2024 13:32:25

t2 = cos(theta);
t3 = sin(theta);
t4 = x.^2;
t5 = xs1.^2;
t6 = y.^2;
t7 = ys1.^2;
t8 = z.^2;
t9 = zs1.^2;
t10 = x.*xs1.*2.0;
t11 = x.*ys1.*2.0;
t12 = xs1.*y.*2.0;
t13 = y.*ys1.*2.0;
t14 = z.*zs1.*2.0;
t15 = -t12;
t16 = -t14;
t17 = t10+t13;
t18 = t11+t15;
t19 = t2.*t17;
t20 = t3.*t18;
t21 = -t19;
t22 = t4+t5+t6+t7+t8+t9+t16+t20+t21;
H = [sqrt(t22);1.0./sqrt(t22).*(u.*x+v.*y+w.*z-w.*zs1-t2.*(u.*xs1+v.*ys1)+t3.*(u.*ys1-v.*xs1)+t2.*thetadot.*(x.*ys1-xs1.*y)+t3.*thetadot.*(x.*xs1+y.*ys1))];
end
